const PATH = {
  HOME: "/",
  LOGIN: "/login",
  SIGN_UP: "/sign-up",
  VERIFY_SIGN_UP: "/sign-up/verify",
  PROFILE: "/profile",
  EDIT_PROFILE: "/edit-profile",
  FORGET_PASSWORD: "/forget-password",
  RESET_PASSWORD: "/reset-password",
  TENANT_LOGIN: "/tenant/login",
  TENANT_SIGN_UP: "/tenant/sign-up",
  PRICE_PLAN: "/pricing",
  PAYMENT_SETTINGS: "/payment-settings",
  PURCHASE_SUCCESS: "/purchase-success",
  LANDLORD_DASHBOARD: "/landlord/dashboard",
  LANDLORD: "/landlord",
  ADD_NEW_OASIS: "/add-new-oasis",
  UPDATE_OASIS: "/update-oasis",
  LIST_TYPE_OASIS: "/list-type-oasis",
  LIST_INCLUDE_FEATURE: "/list-include-feature",
  VIEWING_AVAILABILITY: "/viewing-availability",
  WEEKLY_AVAILABILITY: "/weekly-availability",
  CREATE_NEW_OASIS: "/create-new-oasis",
  LANDLORD_VERIFY_SIGN_UP: "/sign-up/verify",
  LANDLORD_MAINTENANCE: "/landlord/maintenance",
  LANDLORD_LEASES_BUILDER: "/landlord/leases-builder",
  LANDLORD_LEASES_BUILDER_PROPERTY_INFORMATION:
    "/landlord/leases-builder/property-information",
  LANDLORD_LEASES_BUILDER_PROPERTY_TIME:
    "/landlord/leases-builder/property-time",
  LANDLORD_LEASES_BUILDER_TENANT_INFO: "/landlord/leases-builder/tenant-info",
  LANDLORD_LEASES_BUILDER_RENT_MONEY: "/landlord/leases-builder/rent-money",
  LANDLORD_LEASES_BUILDER_LEASES_REVIEW:
    "/landlord/leases-builder/leases-review",
  LANDLORD_LEADS: "/landlord/leads",
  LANDLORD_LEADS_INVITE: "/landlord/leads/invite",
  LANDLORD_LEADS_VIEWING_APPOINTMENTS: "/landlord/leads/viewing-appointments",
  LANDLORD_APPLICANTS: "/landlord/applicants",
  LANDLORD_TENANTS: "/landlord/tenants",
  NOT_FOUND: "*",
};

export default PATH;
